//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ad()
        {
            this.Photos = new HashSet<Photos>();
            this.Tags = new HashSet<Tags>();
            this.Favourite = new HashSet<Favourite>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public float Price { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date_start { get; set; }
        public int SizeId { get; set; }
        public int ColorId { get; set; }
        public int SubcategoryId { get; set; }
        public int ConditionId { get; set; }
        public Nullable<bool> Swap { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<bool> Is_sold { get; set; }
        public Nullable<System.DateTime> Date_end { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Size Size { get; set; }
        public virtual Color Color { get; set; }
        public virtual User User { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourite> Favourite { get; set; }
    }
}
